def raise_exception():
    try:
        pass
    except TypeError:
        print("Exception raised")